[kovi-plugin-bot-check]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[kovi-plugin-bot-check.access_list]
friends = []
groups = []

[chat_message]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[chat_message.access_list]
friends = []
groups = []

[kovi-plugin-check-alllong]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[kovi-plugin-check-alllong.access_list]
friends = []
groups = []

[kovi-plugin-javascript-shell]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[kovi-plugin-javascript-shell.access_list]
friends = []
groups = []

[kovi-plugin-qq-tools]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[kovi-plugin-qq-tools.access_list]
friends = []
groups = []

[kovi-plugin-emoji-attack]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[kovi-plugin-emoji-attack.access_list]
friends = []
groups = []

[kovi-plugin-command-exec]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[kovi-plugin-command-exec.access_list]
friends = []
groups = []
